### ISSUE TITLE
Build fails: Error (warning 70 [missing-mli]): Cannot find interface file.

### ISSUE THREAD

**Issue by yurivict** [abella-prover/abella#154]
Build fails on some systems:
```
ocamlfind ocamlc -c -bin-annot -strict-formats -w @a-4-29-40-41-42-44-45-48-58-59-60 -I src -I test/ext -o src/extensions.cmo src/extensions.ml
+ ocamlfind ocamlc -c -bin-annot -strict-formats -w @a-4-29-40-41-42-44-45-48-58-59-60 -I src -I test/ext -o src/extensions.cmo src/extensions.ml
File "src/extensions.ml", line 1:
Error (warning 70 [missing-mli]): Cannot find interface file.
Command exited with code 2.
gmake: *** [Makefile:7: all] Error 10
===> Compilation failed unexpectedly.
```

[log](https://pkg-status.freebsd.org/beefy18/data/main-amd64-default/p65ec83d48838_s77c3e564b4b/logs/abella-2.0.7.log)

Version: 2.0.7
ocaml-4.14.1
FreeBSD 14.0

**Comment by chaudhuri** [comment]
Is there a specific reason you are trying to build 2.0.7? 2.0.8 has been out for several months now.

**Comment by yurivict** [comment]
2.0.8 depends on specific versions of ocaml-dune which isn't available in FreeBSD ports due to conflicts with other ocaml packages.

ocaml-dune-3.7.1 that is available isn't compatible with 2.0.8

**Comment by chaudhuri** [comment]
Let me check if 2.0.8 compiles with Dune 3.7.1 specifically. A priori it should since it only has `(lang dune 3.7)`.

**Comment by chaudhuri** [comment]
Looks like the `master` branch builds with Dune 3.7.1 and works fine at least on Linux. I can release this as Abella 2.0.8.1 if you want. The 2.0.9 release is still a while away.

**Comment by chaudhuri** [comment]
Please see if [the 2.0.8.1 release](https://github.com/abella-prover/abella/releases/tag/v2.0.8.1) builds for you.

**Comment by yurivict** [comment]
2.0.8.1 fails:
```
dune build src/abella.exe src/abella_doc.exe src/abella_dep.exe
File "src/dune", line 29, characters 34-38:
29 |  (libraries unix re yojson base64 curl)
                                       ^^^^
Error: Library "curl" not found.
-> required by library "abella_lib" in _build/default/src
-> required by executable abella in src/dune:2
-> required by _build/default/src/abella.exe
gmake: *** [Makefile:7: all] Error 1          
```

curl-8.7.1 is installed.

**Comment by chaudhuri** [comment]
Is the OCaml library `ocurl` installed? The dependencies are listed in `abella.opam` -- please make sure all the libraries with their minimum versions are available.

**Comment by chaudhuri** [comment]
Closing this. Please use the 2.0.8.3 release for now which has the libcurl dependency removed. We will revisit this in 2.0.9.
